### ISSUE TITLE
Use emoji images

### ISSUE THREAD

**Issue by IonicaBizau** [muan/emoji-minesweeper#2]
This is how it looks on my machine:

![image](https://cloud.githubusercontent.com/assets/2864371/7785278/da9fac46-0191-11e5-8f59-92eaa1baae7e.png)

I see that it uses the `AppleColorEmoji` font, but that is not loaded on my machine.

![image](https://cloud.githubusercontent.com/assets/2864371/7785288/5302ec8e-0192-11e5-9bc4-6759fca18906.png)

So, what I propose is to use the emoji images. :bomb: Nice project, btw! :smile:

**Comment by muan** [comment]
Added twemoji as an option on top of native ones :sparkles: d51b1c031aa0bccda0ad5b0434f57813f8adca2a

**Comment by IonicaBizau** [comment]
Awww, super nice! :+1: :sparkle:
