### ISSUE TITLE
Shortcut keys✌🏻 for Restart Game💎 ?

### ISSUE THREAD

**Issue by ddemented** [muan/emoji-minesweeper#8]
R for restart. i will work on this after i finish on my jquery!
Btw amazing work , am even trying to make this into an iOS app using Swift as am learning the language, will try no promises haha.

**Comment by ddemented** [comment]
i tried this code in the script, but doesn't seem to work, confused !
  $(window).keydown(function(e) {
    if(e.keyCode == 82) {
      restart
    }
});

**Comment by muan** [comment]
Hi! Sorry for the late reply. That is because there's no jQuery on the page, and I'd prefer that it stay that way. Currently after a game ended, you can just do `shift + tab`, and `enter` to restart the game. But I agree a shortcut might be nice.
